# Generated by Django 6.0.5 on 2026-06-21 13:08

import aibusiness.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aibusiness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', aibusiness.models.UserManager()),
            ],
        ),
    ]
