# Generated by Django 6.0.5 on 2026-06-23 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibusiness', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_package_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserPackageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('package_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_accesses', to='aibusiness.packageplan')),
                ('source_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_access', to='aibusiness.packageorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserServiceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_accesses', to='aibusiness.service')),
                ('source_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accesses', to='aibusiness.packageorder')),
                ('source_package_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accesses_from_package', to='aibusiness.userpackageaccess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTrainingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('package', 'From package'), ('direct', 'Direct purchase'), ('admin', 'Admin grant')], default='direct', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_accesses_from_order', to='aibusiness.packageorder')),
                ('source_package_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_accesses_from_package', to='aibusiness.userpackageaccess')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_accesses', to='aibusiness.trainingprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='userpackageaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'package_plan'), name='unique_user_package_access'),
        ),
        migrations.AddConstraint(
            model_name='userserviceaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'service'), name='unique_active_user_service_access'),
        ),
        migrations.AddConstraint(
            model_name='usertrainingaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'training_program'), name='unique_user_training'),
        ),
    ]
