# Generated by Django 6.0.5 on 2026-06-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibusiness', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=130, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('level', models.CharField(choices=[('initial', 'Initial team training'), ('role_based', 'Role-based training'), ('academy', 'AI Academy'), ('champions', 'Internal champions')], default='initial', max_length=30)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('target_audience', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
