# Generated by Django 6.0.5 on 2026-06-26 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibusiness', '0003_packageorder_approved_at_packageorder_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
