# Generated by Django 6.0.5 on 2026-07-28 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibusiness', '0004_alter_packageorder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('expected_result', models.TextField()),
                ('estimated_hours', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_scenarios', to='aibusiness.service')),
            ],
        ),
    ]
