# Generated by Django 6.0.5 on 2026-06-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibusiness', '0004_trainingprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAiBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order', 'key'),
            },
        ),
    ]
