# Generated by Django 6.0.5 on 2026-06-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibusiness', '0005_aboutaibusiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('max_services', models.PositiveSmallIntegerField(choices=[(1, 'Choose 1 services'), (3, 'Choose 1-3 services'), (5, 'All services open for you')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('included_trainings', models.ManyToManyField(blank=True, related_name='package_plans', to='aibusiness.trainingprogram')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
