# Generated by Django 6.0.5 on 2026-06-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibusiness', '0006_packageplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageplan',
            name='badge',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='best_for_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='best_for_title',
            field=models.CharField(default='Best suited for', max_length=100),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='button_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='includes_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='packageplan',
            name='includes_title',
            field=models.CharField(default='What is included', max_length=100),
        ),
        migrations.AlterField(
            model_name='packageplan',
            name='max_services',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Choose 1 service'), (3, 'Choose 1-3 services'), (5, 'All services open for you')], default=1),
        ),
    ]
