# Generated by Django 6.0.5 on 2026-06-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibusiness', '0007_packageplan_badge_packageplan_best_for_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('in_review', 'IN REVIEW'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='aibusiness.packageplan')),
                ('selected_services', models.ManyToManyField(blank=True, related_name='package_orders', to='aibusiness.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
